name: CI for Spring Boot Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настройка JDK 
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Шаг 3: Скачивание зависимостей и запуск тестов с Maven
      - name: Build with Maven
        run: mvn clean verify --no-transfer-progress

      # Шаг 4: Генерация отчёта о покрытии тестами (с использованием JaCoCo)
      - name: Upload test coverage report
        if: success()
        uses: codecov/codecov-action@v3
        with:
          file: ./target/site/jacoco/jacoco.xml
